name: "Deploy to server"

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader --no-dev --no-interaction

      - name: Install NPM dependencies
        run: npm install

      - name: Deploying to server
        env:
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_dir: ${{ secrets.REMOTE_TARGET }}
          local_dir: "."
        run: |
          rm -rf .git*
          mkdir -p ~/.ssh
          echo "$remote_key" > ~/.ssh/id_github
          chmod 600 ~/.ssh/id_github
          rsync -avzr --delete -e "ssh -i ~/.ssh/id_github -o StrictHostKeyChecking=no" ${local_dir} ${remote_user}@${remote_host}:${remote_dir} --filter='P .env'
          ssh -i ~/.ssh/id_github -o StrictHostKeyChecking=no ${remote_user}@${remote_host} "cd ${remote_dir} && chmod 775 storage storage/logs storage/framework/{cache,sessions,testing,views}"
          rm ~/.ssh/id_github
